name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Static check imports
        run: |
          python -c "__import__('importlib').import_module('fastapi'); __import__('importlib').import_module('requests')"

      - name: Build Docker images
        run: |
          docker build -f docker/webhook.Dockerfile -t prscan-webhook:ci .
          docker build -f docker/dashboard.Dockerfile -t prscan-dashboard:ci .

